### ISSUE TITLE
Bad formatting on bentoml sample in community

### ISSUE THREAD

**Issue by julz** [knative/docs#3762]
See https://knative.dev/community/samples/serving/machinelearning-python-bentoml/ in current (hugo) docs.

Search for ```bash. Also notice the yaml inline and without a code block in the "Building and deploying the sample" section.

**Comment by soham283** [comment]
@julz  is this issue is open or has been resolved ??

**Comment by julz** [comment]
Yes, looks like this is still an issue, see e.g:

![image](https://user-images.githubusercontent.com/354013/125412506-e7f3ce00-e3b6-11eb-95ac-1d77a356e6ec.png)
(should be in code block)

and 

![image](https://user-images.githubusercontent.com/354013/125412243-9ea37e80-e3b6-11eb-81d5-16da912627b8.png)
("Run the `main.py` file to train the model" shouldn't be in a code block, and the ````bash` text should not be visible in the output)

One thing to note for anyone picking this up is the community samples are still built with Hugo rather than MkDocs, so the normal preview won't work  and to reproduce locally you'd need to do a full `./hack/build.sh serve`

**Comment by abrennan89** [comment]
@julz I feel like we should either move the Community section to the new site before working on this or pull out the samples from this section and add them elsewhere in the admin or dev guides?
