### ISSUE TITLE
When search bar is expanded it causes top section titles to be scrunched

### ISSUE THREAD

**Issue by dprotaso** [knative/docs#6332]
You can see in the below image the top section titles and version picker and skewed

<img width="1307" height="412" alt="Image" src="https://github.com/user-attachments/assets/722f9daa-63c1-41e4-a06b-b3194414a6eb" />

**Comment by dprotaso** [comment]
cc @thisisobate

**Comment by rohan-019** [comment]
I noticed that this header misalignment doesn’t happen when running knative/docs locally — it only shows up on the deployed site. 

Could someone from the team confirm if this is managed outside of knative/docs ?

cc @dprotaso @thisisobate

**Comment by dprotaso** [comment]
hey @rohan-019 - I think the netlify preview doesn't use this script - https://github.com/knative/docs/blob/main/hack/build.sh

**Comment by rohan-019** [comment]
Thanks for clarifying! That makes sense — I’ll start working on this issue and explore updating the Netlify build config to use build.sh so it matches the local environment. I’ll share updates here.
cc @dprotaso

**Comment by lakxy** [comment]
Hi @evankanderson @dprotaso 
I have checked the issue against the official website, It seems it has been resolved,
Please verify,
I believe, this issue can be closed.

Thank you.

**Comment by dprotaso** [comment]
@codeEvolveZenith345 what browser are you using? I still see it on `knative.dev`

https://github.com/user-attachments/assets/60a5a070-3d7c-4895-902b-fbf29da1161a

**Comment by lakxy** [comment]
Hi @dprotaso 
I experienced the same behavior as you attached in screen recording, But the version overlap with the nav attributes is no longer persisting as was in the image in the description...
There is no activity from @rohan-019 , perhaps he might link a PR as assignee,

@dprotaso However, what is the expected outcome to resolve the issue?

**Comment by dprotaso** [comment]
Hey @codeEvolveZenith345 I think we should keep things simple and just have the navigation remain static.

For example visit the website of the theme we are using. https://squidfunk.github.io/mkdocs-material/tutorials/

When you click on the search bar it expands and is over top of the navigation

**Comment by lakxy** [comment]
> Hey @codeEvolveZenith345 I think we should keep things simple and just have the navigation remain static.

Ageed!
> For example visit the website of the theme we are using. https://squidfunk.github.io/mkdocs-material/tutorials/

This looks good for reference but, The current content does not align with this reference, I mean 
  currently search bar expansion on `/knative.dev` hides the title too, here in the reference the title is unchanged, 
Also. about the elements beside the searchbar like Home etc, are not in the reference, 
So I guess you mean:
- keep the title,
- expand the searchbar
- searchbar should overlay the elements  like Home etc,
 
@dprotaso should we wait for @rohan-019 ? As he was assigned, although there is no activity on it since a long time...

**Comment by dprotaso** [comment]
@rohan-019 are you still working on this?

**Comment by rohan-019** [comment]
Hey @codeEvolveZenith345 — I’m not working on this at the moment, so feel free to take it over.

**Comment by lakxy** [comment]
> > Hey [@codeEvolveZenith345](https://github.com/codeEvolveZenith345) I think we should keep things simple and just have the navigation remain static.
> 
> Ageed!
> 
> > For example visit the website of the theme we are using. https://squidfunk.github.io/mkdocs-material/tutorials/
> 
> This looks good for reference but, The current content does not align with this reference, I mean currently search bar expansion on `/knative.dev` hides the title too, here in the reference the title is unchanged, Also. about the elements beside the searchbar like Home etc, are not in the reference, So I guess you mean:
> 
> * keep the title,
> * expand the searchbar
> * searchbar should overlay the elements  like Home etc,
> 

Hi @dprotaso 
Please answer these follow-ups for me to work in an accurate direction!

**Comment by lakxy** [comment]
Hi! @dprotaso I am waiting for your confirmation...

**Comment by dprotaso** [comment]
>  I guess you mean:
>
> keep the title,
> expand the searchbar
> searchbar should overlay the elements like Home etc,

Yeah that sounds good

**Comment by jijo-OO7** [comment]
I believe the issue has been resolved. I verified the behavior on the mobile view, and the search bar now works as expected, consistent with the reference implementation: https://squidfunk.github.io/mkdocs-material/tutorials/.

**Comment by dprotaso** [comment]
It's not resolved - the bar pushes content around 

<img width="1306" height="229" alt="Image" src="https://github.com/user-attachments/assets/99b978db-3241-44aa-8e7e-b7602f5a7c8d" />

**Comment by lakxy** [comment]
Hi @dprotaso I have tried fixing it in the draft PR linked here, but I was not able to resolve it, if one thing worked another broke.
Over to you @jijo-OO7

**Comment by jijo-OO7** [comment]
Hi @dprotaso   I’ve opened PR #6556 to address this.

The change ensures the search bar expands as an overlay without pushing or reflowing the header content, aligning with the reference behavior from the mkdocs-material theme.

I’ve verified this on mobile and desktop views. Could you please take a look and let me know if this now matches the expected behavior, or if there’s still a specific case I should adjust

Thank You !
